// Automatically generated by MockGen. DO NOT EDIT!
// Source: ../../server/ctrl/ready.go

package mock_ctrl

import (
	. "github.com/ghilbut/ygg.go/common"
	gomock "github.com/golang/mock/gomock"
)

// Mock of TargetReadyDelegate interface
type MockTargetReadyDelegate struct {
	ctrl     *gomock.Controller
	recorder *_MockTargetReadyDelegateRecorder
}

// Recorder for MockTargetReadyDelegate (not exported)
type _MockTargetReadyDelegateRecorder struct {
	mock *MockTargetReadyDelegate
}

func NewMockTargetReadyDelegate(ctrl *gomock.Controller) *MockTargetReadyDelegate {
	mock := &MockTargetReadyDelegate{ctrl: ctrl}
	mock.recorder = &_MockTargetReadyDelegateRecorder{mock}
	return mock
}

func (_m *MockTargetReadyDelegate) EXPECT() *_MockTargetReadyDelegateRecorder {
	return _m.recorder
}

func (_m *MockTargetReadyDelegate) OnTargetProxy(ctrl *CtrlProxy, target *TargetProxy) {
	_m.ctrl.Call(_m, "OnTargetProxy", ctrl, target)
}

func (_mr *_MockTargetReadyDelegateRecorder) OnTargetProxy(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "OnTargetProxy", arg0, arg1)
}
