// Automatically generated by MockGen. DO NOT EDIT!
// Source: ../../common/ready.go

package mock_common

import (
	. "github.com/ghilbut/ygg.go/common"
	gomock "github.com/golang/mock/gomock"
)

// Mock of CtrlReadyDelegate interface
type MockCtrlReadyDelegate struct {
	ctrl     *gomock.Controller
	recorder *_MockCtrlReadyDelegateRecorder
}

// Recorder for MockCtrlReadyDelegate (not exported)
type _MockCtrlReadyDelegateRecorder struct {
	mock *MockCtrlReadyDelegate
}

func NewMockCtrlReadyDelegate(ctrl *gomock.Controller) *MockCtrlReadyDelegate {
	mock := &MockCtrlReadyDelegate{ctrl: ctrl}
	mock.recorder = &_MockCtrlReadyDelegateRecorder{mock}
	return mock
}

func (_m *MockCtrlReadyDelegate) EXPECT() *_MockCtrlReadyDelegateRecorder {
	return _m.recorder
}

func (_m *MockCtrlReadyDelegate) OnCtrlProxy(proxy *CtrlProxy) {
	_m.ctrl.Call(_m, "OnCtrlProxy", proxy)
}

func (_mr *_MockCtrlReadyDelegateRecorder) OnCtrlProxy(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "OnCtrlProxy", arg0)
}
